title: "مجله علمی من"
description: "بررسی مقاله‌ها و مطالب علمی"
baseurl: ""
url: "https://sargdsra.github.io"
markdown: kramdown
highlighter: rouge

# تنظیمات Collections
collections:
  papers:
    output: true
    permalink: /papers/:title/
  posts:
    output: true
    permalink: /blog/:title/

# تنظیمات پیش‌فرض
defaults:
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "paper"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# تنظیمات فونت
font:
  primary: "Vazir"
  code: "Fira Code"